### ISSUE TITLE
Add test case for bin_counter being < 8 chars

### ISSUE THREAD

**Issue by reedy** [jakobo/hotp-php#12]
As of writing, only https://github.com/Jakobo/hotp-php/blob/ea29559/src/HOTP.php#L34-L37 is untested

Not a big deal, but would be nice to get 100% coverage sometime ;)

**Comment by jakobo** [comment]
It might be a year (and change) late, but yes, we should go for 100% coverage. I'll see about getting the final test in this weekend.

**Comment by jakobo** [comment]
It's about 6 months late, but here we go with 100% coverage. :) #17 has the fix; moved to a safer str_pad instead of a str_repeat, which removes the unnecessary `if` block
