### ISSUE TITLE
Automated Syntax Formatting on Commit

### ISSUE THREAD

**Issue by jakobo** [jakobo/hotp-php#14]
I've been out of the PHP game for a while, and the tooling in composer has simply gotten _much_ better. So that future commits and code are protected against awkward `{` and `}` placement, we should use something to automate the formatting of commit code instead of relying on VS Code to do the heavy lifting.

Ideally, we'd use something like [GrumPHP](https://github.com/phpro/grumphp), directly use PHP-CS-Fixer, or add Husky/Lint-Staged tasks via node.

/cc @jrzepa in case I'm missing anything from #13 where the original commit was to get our code standards up to par

**Comment by RishiKumarRay** [comment]
do we need to add this via CI?

**Comment by reedy** [comment]
I'm not sure how you're planning on doing this, but commit hooks get painful for sure.

Nothing against having CI reject a patch for it not being upto standards :)

**Comment by jakobo** [comment]
Looked around to see what's out there. I don't think we'd run in CI. I'd rather silently format on commit. This way, people don't have to worry about their syntax. 

This solution is based on how many node projects manage code quality with prettier + husky.

1. Add [composer-git-hooks](https://github.com/BrainMaestro/composer-git-hooks) to our composer.json. This gives us a way to run pre commit hooks reliably.
2. Set up [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) to PSR-12. Add a command to composer that lets us reliably run syntax cleaning via `composer exec`
3. Add a pre-commit hook that runs  php-cs-fixer and re adds changes with `git add -A`

**Comment by jrzepa** [comment]
> I'm not sure how you're planning on doing this, but commit hooks can get painful for sure.

I agree with that. 

> Looked around to see what's out there. I don't think we'd run in CI. I'd rather silently format on commit. This way, people don't have to worry about their syntax.

It depends on what IDE you are using. For example PHPStorm supports PSR-12 standard and detects and integrates with PHP-CS-Fixer tool (if install via composer). There is no need to use pre-commit.  I thinkt that define command for syntax fix in composer is a sufficient solution or just checking syntax via CI.

I am aware that not every one using PHPStorm :D 

I checked and the newest version of Php-CS-Fixer works with 7.4 and 8.0. Thats why my previous commit failed.

**Comment by jakobo** [comment]
I think it's an easy enough fix for the 7.2/7.3 versions. Because our composer file uses only dev dependencies, I'm happy to add the `--ignore-platform-reqs` flag to our workflow. I've put together #16 which uses hooks that are set up as part of the composer install. Would love if folks could take a look at it. Nothing about these changes warrants a release, but it's always nice to keep the code quality up.
